title: Introduction
description: an Explanation

author:
  name: Doanh Luu Nguyen
  
social-network-links:
  rss: true
  email: "dlncg4602@gmail.com"
  github: yon-ln
  

plugins:
  - jekyll-paginate
  - jekyll-sitemap
